name: cat_breeds_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.10
  http: ^1.2.0
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  get_it: ^7.6.7
  flutter_bloc: ^8.1.3
  page_transition: ^2.1.0
  flutter_svg: ^2.0.9

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#89759C"
  color_dark: "#89759C"
  image: assets/logo/logo-splash.png
  image_dark: assets/logo/logo-splash.png

  android_12:
    image: assets/logo/logo-splash.png
    icon_background_color: "#89759C"
    image_dark: assets/logo/logo-splash.png
    icon_background_color_dark: "#89759C"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/

  fonts:
    - family: onest-cyrillic
      fonts:
        - asset: assets/fonts/onest-cyrillic-200-normal.ttf
        - asset: assets/fonts/onest-cyrillic-300-normal.ttf
        - asset: assets/fonts/onest-cyrillic-400-normal.ttf
        - asset: assets/fonts/onest-cyrillic-500-normal.ttf
        - asset: assets/fonts/onest-cyrillic-600-normal.ttf
        - asset: assets/fonts/onest-cyrillic-700-normal.ttf
          style: normal
